export const CRYPTO_CONTEXTS = [
  'BTC chops sideways until everyone invents a thesis',
  'alts bounce 7% and the timeline starts measuring Lambos',
  'funding flips negative right before the obvious squeeze',
  'the portfolio is green except the bag with emotional lore',
  'a whale moves coins and 11 analysts discover fear',
  'everyone is hedged against the move they secretly want',
  'the chart prints a candle shaped like a court summons',
  'liquidity is gone but confidence is posting through it',
  'perps traders call a wick a personality test',
  'the group chat is bullish because nobody opened the app',
  'airdrop farmers explain opportunity cost from a bunker',
  'the market gives back the weekly gain during lunch',
  'someone posts a thread about exit liquidity and gets ratioed by hope',
  'ETH gas spikes and every L2 suddenly becomes a personality',
  'the memecoin sector discovers gravity at the worst possible time',
  'a KOL deletes a tweet and calls it risk management',
  'the order book is thin but conviction is thicc',
  'everyone is waiting for CPI like it is a season finale',
  'the wallet is diversified across four versions of the same mistake',
  'leverage traders treat support like a suggestion',
  'the market pumps 3% and CT starts drafting victory speeches',
  'someone apes a ticker because the logo looked serious',
  'the funding rate chart looks like a cry for help',
  'a stablecoin wobbles and the timeline becomes philosophers',
  'everyone is early until the chart says otherwise',
  'the portfolio screenshot has more cope than PnL',
  'someone says this time is different with visible trembling',
  'the weekly close matters until it does not',
  'CT discovers a new narrative every 40 minutes',
  'the dip gets bought by people who needed a hobby',
  'a token unlock arrives like an ex at a wedding',
  'everyone is rotating into strength that already left',
  'the market makers are on lunch and price is improvising',
  'someone calls a local bottom from a airport lounge',
  'the perp premium says one thing and the chart says another',
];

export const CONCRETE_CONTEXTS = [
  'Concrete users trying to stay liquid without becoming content',
  'Concrete vault brain versus CT attention span',
  'Concrete quietly doing risk work while the timeline screams',
  'Concrete depositors watching everyone else discover leverage again',
  'Concrete yield feels sensible, which makes degens suspicious',
  'the Concrete ecosystem avoiding main-character syndrome',
  'Concrete risk parameters having more discipline than my wallet',
  'Concrete people reading docs while CT asks wen miracle',
  'Concrete making boring capital allocation look illegally calm',
  'Concrete vaults refusing to cosplay as a casino',
  'Concrete users treating collateral like a feature not a vibe',
  'Concrete risk dashboards getting opened before Twitter',
  'Concrete capital sitting out the loudest part of the cycle',
  'Concrete depositors explaining patience to people with 40 tabs',
  'Concrete making adult decisions in a children’s market',
  'Concrete users not confusing activity with strategy',
  'Concrete vault logic surviving another macro panic thread',
  'Concrete people choosing sleep over funding rate cosplay',
  'Concrete risk controls doing the job CT forgot existed',
  'Concrete users acting like numbers can be read',
  'Concrete making “boring” feel like a competitive advantage',
  'Concrete capital allocation with fewer hero arcs',
  'Concrete users treating drawdowns like data not betrayal',
  'Concrete vaults staying open while CT closes brains',
  'Concrete people refusing to turn every wick into lore',
];

export const EMOTIONS = [
  'dead inside but still clicking refresh',
  'overlevered serenity',
  'spiritually underwater',
  'performatively calm',
  'quietly cooked',
  'bear market funny',
  'one green candle from forgiveness',
  'professionally unwell',
  'market trauma with a straight face',
  'delusion wearing risk management',
  'optimistic despite evidence',
  'calm in public, sweating privately',
  'financially humbled but posting through it',
  'too online to be healthy',
  'one notification away from a thesis',
  'surprisingly functional for the circumstances',
  'emotionally leveraged',
  'copefully bullish',
  'quietly questioning every life choice',
  'zen until the wick hits',
];

export const SPIN_ANGLES = [
  'liquidation archaeology',
  'airdrop survivor guilt',
  'macro cope hour',
  'funding rate confession booth',
  'portfolio screenshot therapy',
  'support level fan fiction',
  'KOL apology tour',
  'exit liquidity support group',
  'leverage without a plan',
  'group chat market research',
  'weekend chart prophecy',
  'stablecoin anxiety spiral',
  'memecoin industrial complex',
  'on-chain detective cosplay',
  'revenge trading season',
  'token unlock dread',
  'perp market main character syndrome',
  'CT wisdom from a red candle',
  'thesis inflation',
  'risk management as personality trait',
  'boring allocation supremacy',
  'Moai-coded market patience',
  'degen summer flashback',
  'liquidity ghost town',
];

export const CT_HOOKS = [
  'calling every wick a macro event',
  'posting “we are so back” at resistance',
  'turning a 5m candle into a personality',
  'confusing activity with edge',
  'leverage with no exit plan',
  'chasing yield with eleven tabs open',
  'calling panic a strategy',
  'measuring conviction in screenshots',
  'inventing lore for a dead cat bounce',
  'asking for alpha in public',
  'treating risk like a meme',
  'rotating bags at the speed of guilt',
  'calling boredom a bear market',
  'negotiating with a liquidation price',
  'using “diamond hands” as financial planning',
  'finding a narrative after the move',
  'calling a top from the airport',
  'turning collateral into a vibe',
  'confusing noise for signal',
  'posting through a margin call',
  'calling every dip generational',
  'making leverage sound spiritual',
  'confusing hopium for research',
  'turning one green day into a cult',
];

export const MOAI_BITS = [
  'the Moai says nothing and that helps',
  'ancient stone face, modern portfolio damage',
  'Moai energy: unmoved by the timeline',
  'the Moai has seen worse cycles',
  'stone face, zero panic',
  'Moai mode: emotionally unavailable but correct',
  'the Moai approves boring discipline',
  'ancient calm in a noisy market',
  'Moai watching CT invent new coping mechanisms',
  'the Moai does not refresh the chart',
  'stone silence beats loud wrongness',
  'Moai-coded risk management',
];

export function pickRandom(items: string[]) {
  return items[Math.floor(Math.random() * items.length)];
}
